### ISSUE TITLE
Good idea. I wonder if the data is local? Can it be synchronized across devices?

### ISSUE THREAD

**Issue by bfrontend** [codeacme17/marktodo#5]

**Comment by codeacme17** [comment]
Yes, currently the data is stored locally in the browser. This is indeed a pain point, and I'm also thinking about how to make a synchronization feature, such as leveraging the capabilities of some database platforms? Let users create their own libraries and fill in the api key?Or maybe I deploy a server myself to supply the users? I haven't decided yet, if you have any good ideas you can also put forward!
